config/routes.rb
Myp::Application.routes.draw do
  get "clas/create"
  get "clas/destroy"
  get "clas/update"

resources :users do
    member do
      get 'select_type'
      patch 'update_type'
      get 'select_school'
      get 'qschbyname', to: 'schools#search_by_name'
      get 'qschbylocation', to: 'schools#search_by_location'
    end
  end
  resources :sessions, only: [:new, :destroy, :create]
  resources :schools, only: [:new, :destroy, :create, :edit, :update ] do
	collection do
		get 'admin'
	end
	  member do	
		get 'adclas'
		get 'addem'
		get 'adbas'
		resource :demonstrate, path: '/admin/demonstrate'
  		resources :grades, path: '/admin/grades'
		resources :clas, path: '/admin/clas'
	  end
  end
  root to: "static_pages#home"

  

  mount ChinaCity::Engine=>'/china_city'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :school
end

app/models/cla.rb
class Cla < ActiveRecord::Base
	validates :name, uniqueness: true
	belongs_to :grade
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	belongs_to :school
	has_many :clas
end

app/models/school.rb
class School < ActiveRecord::Base
	belongs_to :user
	has_one :address
	has_many :grades
end

app/models/user.rb
class User < ActiveRecord::Base

 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
 validates :name, presence: true, length: {maximum: 50}
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX} , uniqueness: {case_sensitive: false} 
 has_secure_password

 has_one :school

 before_save {self.email = email.downcase}

 def User.new_remember_token
	 SecureRandom.urlsafe_base64
 end

 def User.encrypt(token)
	 Digest::SHA1.hexdigest(token.to_s)
 end
 
 private
 def create_remember_token
	 self.remember_token = User.encrypt(User.new_remember_token)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/clas_controller.rb
class ClasController < ApplicationController
  def create
   	@cla = Cla.new(params[:cla].permit(:name))
	@cla.grade = Grade.find(params[:gid])
	@clas = Grade.find(params[:gid]).clas
	@gid = params[:gid]
	
	if @cla.save
		respond_to do |format|
			format.js
		end
	else
		respond_to do |format|
			format.html{redirect_to adclas_school_path(current_user.school) }
		end
	end
  end

  def destroy
  end

  def update
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
	def create
		grade = Grade.new(params[:grade].permit(:name))
		grade.school = current_user.school
		if grade.save
			@grades = current_user.school.grades
			@cla = grade.clas.new
	  		respond_to do |format|
				format.js
			end
		else
			respond_to do |format|
				format.html{redirect_to adclas_school_path(current_user.school) }
			end
		end

			
	end
end

app/controllers/schools_controller.rb
# coding: utf-8
class SchoolsController < ApplicationController
  def create
	  @school = School.new(school_params)
	  @school.user = current_user
	  province = ChinaCity.get(params[:province])
	  city = ChinaCity.get(params[:city])
	  district = ChinaCity.get(params[:district])
	  @school.location = province+city+district+@school.location
	  if @school.save
		Address.new(province: province, city: city, district: district, school: @school).save
		redirect_to root_url(current_user)
	  else
		  render 'schools/new'
	  end
  end

  def new
	  @school = School.new
  end

  def update
	  @school = School.find(params[:id])
	  if @school.update_attributes(school_params)
		  flash[:success] = "幼儿园信息更新成功!"
		  redirect_to root_url(current_user)
	  else
		  render 'edit'
	  end

  end
  
  def edit
	  @school = School.find(params[:id])
  end
 
  def admin
	  @school = School.new
	  @school.user = current_user
	  if !current_user.school.nil?
		  @school = current_user.school
	  end
  end
  
  def destroy
  end

  #admin basic informations
  def adbas
  end
  #admin demonstrate pages
  def addem
  end
  

  # admin classes in this school
  def adclas
  	@grade = Grade.new
	@grades = current_user.school.grades
	@cla = Cla.new
	
  end

  def search_by_name
  	@schools = School.where(schname: params[:name])
	respond_to do |format|
		format.js
	end
  end

  def search_by_location
 	@schools = School.joins(:address).where("addresses.province like ? and addresses.city like ? and addresses.district like ?","%"+ChinaCity.get(params[:province])+"%","%"+ChinaCity.get(params[:city])+"%","%"+ChinaCity.get(params[:district])+"%")
	respond_to do |format|
		format.js
	end
  end
	 

  private
  def school_params
	  params.require(:school).permit(:schname, :location, :phone)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	  user = User.find_by(email: params[:session][:email].downcase)
	  if user && user.authenticate(params[:session][:password])
		  sign_in user
	  	  redirect_to root_url
	  else
		  flash.now[:error] = 'Invalid email/password combination'
		  render 'new'
  end
  end
  def destroy
	  sign_out
	 redirect_to root_path 
  end
end

app/controllers/static_pages_controller.rb
#encoding: utf-8
class StaticPagesController < ApplicationController
  def home
	 if signed_in?
		 if current_user.user_type == 1
				 redirect_to admin_schools_path
		 end
		 if current_user.user_type == 3
			 redirect_to select_school_user_path(current_user)
		 end
	 else
		 render 'sessions/new'
	 end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
   @user = User.new(user_params)
	if @user.save
	flash[:success] = "注册成功!"
	sign_in @user
	render 'select_type' 
	else
	 render 'new'
	end
  end

  def new
   @user = User.new
  end

  def index
  end

  def show
  end

  def update 
  end

  def select_type
   @user= User.find(params[:id])
  end

  def update_type
   @user = User.find(params[:id])
   type = params[:type]
    
   if type == 'school'
      data = 1
      msg = '幼儿园管理'
   end
  
   if type == 'parent'
	   msg = '家长'
	   data = 2
   end   
  
   if type == 'teacher'
	   msg= '幼师'
	   data = 3
   end   

   if @user.update(user_type: data)
      flash[:success] = "您成功开通了#{msg}服务！"
      redirect_to root_url(@user) 
   else
      flash[:alert] = "您未成功开通#{msg}服务！请重新操作！"
      render 'select_type'
   end
  end


  def select_school
   @schools = []	
  end
  private
   def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
#encoding: utf-8
module SessionsHelper
	
	def current_user=(user)
	
		@current_user = user
	end

	def sign_in(user)

		remember_token = User.new_remember_token

		cookies.permanent[:remember_token] = remember_token

		self.current_user = user

		user.update_attribute(:remember_token, User.encrypt(remember_token))

	end

	def signed_in?
		!current_user.nil?
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url, notice: "请登录!"
		end
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clas/_cla.html.erb
<li>
<div class="cla">
	<%= cla.name %>
</div>
</li>

app/views/clas/create.js.erb
$("#addCla<%=@gid%>").modal('hide')
$("#g<%=@gid%> ul.clas_ul").html("<%= escape_javascript(render(@clas))%>")
init_clasul();

app/views/clas/destroy.html.erb
<h1>Clas#destroy</h1>
<p>Find me in app/views/clas/destroy.html.erb</p>

app/views/clas/update.html.erb
<h1>Clas#update</h1>
<p>Find me in app/views/clas/update.html.erb</p>

app/views/grades/_grade.html.erb
<li>
<div id="g<%= grade.id %>" class="grade"> 
<ul class="ul_float" style="height:30px">
	<li><span id="gtitle"><%= grade.name %></span></li>
	<li style="float:right"><a href="#addCla<%=grade.id%>" role="button" class="btn btn-mini btn-info" data-toggle="modal">添加班级</a></li>
</ul>
<div>
<ul class="clas_ul">
	<%= render(grade.clas) || "这个年级中还没有班级被创建!"%>
</ul>
</div>
<div><span id="show<%=grade.id%>" class="show btn btn-link">显示所有班级</span></div>
</li>
<div id="addCla<%=grade.id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addCla" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h4 id="addCla">添加班级</h4>
	</div>
	<div class="modal-body">
		<%= form_for(@cla, remote: true) do |f|%>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<input type="hidden" name="gid" value="<%= grade.id%>">
			<%= f.submit "创建班级", style: "margin-bottom: 10px; margin-left: 15px;"%>
		<% end %>
	</div>
</div>

app/views/grades/create.js.erb
$(".grades_ul").html("<%= escape_javascript(render(@grades)) %>")
$("#addGrade").modal('hide')
				var showes = $("span.show")
				showes.each(function(){ 
					$(this).click(function(){
						var tmp = $(this).attr("id");
						tmp = tmp.substring(4,tmp.length); 
						$("#g"+tmp+" ul.clas_ul").children(":gt(4)").toggle(100);
					})
				})
init_clasul()

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
	<a href='#'>Designed</a> by 葛晨拓</small>
<nav>
<ul>
	<li><%= link_to "关于", "#"%></li>
	<li><%= link_to "联系我们","#"%></li>
	<li><a href="#">news</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header id="nav" class="navbar navbar-fixed-top">
<div style="background-color:rgb(59,89,152);height:40px;auto;box-shadow:0px 2px 2px -2px rgba(0,0,0,0.52);">
	<div class="offset2 ">
		<a href="#" id="logo">欢迎</a>
		<nav>
		  <div class="input-append">
		<input type="text" value="搜索幼儿园、班级、幼师、家长、孩子..." style="height: 15px;
    margin-top: 7px;
    font-size: small;
    margin-left: 30px;">
            <span class="add-on btn" style="
    margin-top: 7px;
    height: 15px;
"><i class="icon-search"></i></span></div>
		<ul class="pull-right nav">
			<li><a class="navfont" href="/" style="font-size: smaller; color: white;">首页</a></li>
			<li><a href="/users/1/select_type" style="font-size: small; color: white;">开通服务</a></li>
				<li> <a href="#" style="font-size: smaller; color: white;">页面</a></li>
				<li id="fat-menu" class="dropmenu">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="font-size: smaller; color: white;">用户名<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><a href="#">个人资料</a></li>
					<li><a href="#">设置</a></li>
					<li class="divider"></li>
					<li> 
					<a data-method="delete" href="/signout" rel="nofollow">退出登录</a>
					</li>
				</ul>
				</li>
			</ul></nav>
		</div>
	</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myp</title>
 <%= stylesheet_link_tag    "application"  %>
 <%= javascript_include_tag "application", media: "all"%>
 <%= csrf_meta_tags %>
 <%= yield :scripts%>
 <script type="text/javascript">
	$(document).ready(function(){
				$("#nav .nav li").children(":lt(4)").css("font-size","smaller").css("color","white");
			})
 </script>
</head>
<body>
		<%= render 'layouts/header' %>
	<div class="main">
		<div  class="leftsidebar span2">
			<%= yield :leftsidebar%>
		</div>
		<%= yield :login %>
		<%= yield :free%>
		<div class="content span10">
			<%= yield :main %>
		</div>
		<div class="rightsidebar span3">
			<%= yield :rightsidebar%>
		</div>
	</div>

	<%= render 'layouts/footer' %>
	<%= yield :script%>
</body>
</html>

app/views/schools/_schinfo.html.erb
<address>
	<strong><%= school.schname%></strong><br>
	<%= school.address.province+'--'+school.address.city+'--'+school.address.district %><br>
	<abbr title="Phone">P:</abbr> <%= school.phone %>
</address>

app/views/schools/_school.html.erb
<li>
<div class="school">
	<div class="schimg"></div>
	<div class="schinfo">
		<ul class="ul_float">
			<li>		
			<p><%= school.schname%></p>
				<p>地址:<%= school.location%></p>
				<p>电话:<%= school.phone%> </p>
			</li>	
			<li>					
<p><button class="btn" style="width:110px;font-size:medium;font-weight:bolder;color:#8191E5">选择幼儿园</button></p>
			</li>		
			</ul> 
	</div>
			
</div>
</li>

app/views/schools/_schoolform.html.erb
<%-
	province = ''
    
	city = ''
  
	district = ''
	
	provinces  = ChinaCity.list
      
	cities     = ChinaCity.list(province)
    
	districtes = ChinaCity.list(city)
%>
<% content_for :script do %>
 
	<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.5&ak=23f86e79c2a4317be8836304572ae6da"></script>
	<script type="text/javascript">
$(document).ready(function(){
	var map = new BMap.Map("allmap");            
 	var point = new BMap.Point(116.404, 39.915);  

	var marker = new BMap.Marker();
	map.centerAndZoom(point,10); 
	map.enableScrollWheelZoom();  
	map.addControl(new BMap.MapTypeControl());
	map.addControl(new BMap.ScaleControl());
 
 	
	var province='';
	var city='';
	var district='';
	var schname='';
	$("#school_schname").keydown(function(){
	schname=$(this).val();
	var local = new BMap.LocalSearch(province+city+district, {	
	onSearchComplete: function(results){
	var p = results.getPoi(0);
	marker.setPosition(p.point);
	marker.setTitle(p.title);
	map.centerAndZoom(p.point, 17);
	map.addOverlay(marker);
	},pageCapacity: 8});
	local.search(schname);
	});


	$("#province").change(function(){
	province=$(this).children('option:selected').text();
	var local = new BMap.LocalSearch(province+city+district, {	
	onSearchComplete: function(results){
	var p = results.getPoi(0);
	marker.setPosition(p.point);
	marker.setTitle(p.title);
	map.centerAndZoom(p.point, 17);
	map.addOverlay(marker);
	},pageCapacity: 8});
	local.search(schname);
	});
	
/*
$("#city").change(function(){
	city=$(this).children('option:selected').text();
	var local = new BMap.LocalSearch(province+city+district, {	
	onSearchComplete: function(results){
	var p = results.getPoi(0);
	marker.setPosition(p.point);
	marker.setTitle(p.title);
	map.centerAndZoom(p.point, 17);
	map.addOverlay(marker);
	},pageCapacity: 8});
		local.search(schname);
	});
	
$("#district").change(function(){
		
	district=$(this).children('option:selected').text();
	var local = new BMap.LocalSearch(province+city+district, {	
	onSearchComplete: function(results){
	var p = results.getPoi(0);
	marker.setPosition(p.point);
	marker.setTitle(p.title);
	map.centerAndZoom(p.point, 17);
	map.addOverlay(marker);
	},pageCapacity: 8});
	local.search(schname);
	});*/
});	
</script>

<% end %>

<%= form_for( @school ) do |f| %>

	<%= f.label :schname, '幼儿园名称'%>
	<%= f.text_field :schname, class: "input-xlarge" %>
	<br>
	<%= f.label :phone, '联系电话'%>
	<%= f.text_field :phone, class: "input-xlarge" %>
	<br>
	<%= f.label :privince, '地区' %>
	<div class='rails-helper city-group '>
		<ul class="ul_float input-block-level">
			<li>
			<%= select_tag :province, options_for_select(provinces, province) , prompt: '--省份--', class: ['city-select', 'city-province'] %></li>
			<li><%= select_tag :city    , options_for_select(cities, city)        , prompt: '--城市--', class: ['city-select', 'city-city'] %></li>
			<li><%= select_tag :district, options_for_select(districtes, district), prompt: '--地区--', class: ['city-select', 'city-district'] %></li>
		</ul>
	</div>
	<br>
	<%= f.label :location, '街道地址' %>
	<%= f.text_field :location, class: "input-xlarge" %>
	<br>
	<%= f.submit '提交', class: "btn btn-large btn-primary"%>
<% end %>

app/views/schools/adbas.html.erb
<div class="row">
	<%= render 'shared/schsidebar' %>
</div>

app/views/schools/adclas.html.erb
<% content_for :leftsidebar do%>
<%= render 'shared/schsidebar' %>
<% end %>

<% content_for :main do%>
<div class="row"> 
	<div class="span10">
		<a href="#addGrade" role="button" class="btn btn-mini btn-success" data-toggle="modal">添加年级</a>
		<hr style="margin:0 0 0 0;border-top:1px solid gray; margin-top:5px">
		<ul class="grades_ul">
			<%= render(@grades) || "你还没有创建年级。"%>
		</ul>
	</div>
</div>
<div id="addGrade" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addGrade" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h4 id="addGrade">添加年级</h4>
	</div>
	<div class="modal-body">
		<%= form_for(@grade, remote: true) do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.submit "创建年级", style: "margin-bottom:10px;margin-left: 15px;" %>
		<% end %> 
	</div>
</div>

<% end %>
<% content_for :scripts do %>
	<script type="text/javascript">
		$(document).ready(function(){
			init_span();	
		        init_clasul();		

		})
function switchSpan(span){
	if(span.text()=='显示所有班级'){
		span.text('收起');
	}else{
		span.text('显示所有班级');
	}
}
function init_span(){
	var showes = $("span.show");	
	showes.each(function(){ 
			$(this).click(function(){
				$(this).parent().prev().children().children(":gt(4)").toggle(100);
				switchSpan($(this));
				})	
			})	
}
function init_clasul(){
	var grades = $("div ul.clas_ul");

	grades.each(function(){
			var count = $(this).children().size();
			if(count>5){
				$(this).children(":gt(4)").hide();
				$(this).parent().next().children().first().show();
			}else{
				$(this).parent().next().children().first().hide();	
			}
			})

}

	</script>
<% end %>

app/views/schools/addem.html.erb
<div class="row">
	<%= render 'shared/schsidebar' %>
</div>

app/views/schools/admin.html.erb
<% content_for :scripts do %>
	<script type="text/javascript">
	$(document).ready(function(){
		$("#switch_schinfo").click(function(){
			$("#schinfo").toggle();
		});
	});
</script>
<% end %>
<% content_for :leftsidebar do %>
	<%= render 'shared/schsidebar'%>
<% end %>

<div class="content">
<% content_for :main do %>
	<% if current_user.school.nil? %>

		<div class="span5">
			<%= render "schoolform" %>
	
		</div>
		<div class="span5">
			<%= render "shared/map"%>
		</div>

	<% else %>
		
			<div class="span10">
				<ul class="ul_float">
					<li>
						<h4 style="display:block;">幼儿园信息</h4>
					</li>

					<li>
						<a href="javascript:;" id="switch_schinfo" href="#" style="padding-left:15px;font-size: 1em; font-space:2px;">查看</a>
					</li>
				</div>
		
			<div id = "schinfo" class="span10">	
				
				<%= render partial: 'schools/schinfo', locals: {school: current_user.school} %>
		
			</div>
	<%end%>

<% end %>

</div>

app/views/schools/create.html.erb
<h1>Schools#create</h1>
<p>Find me in app/views/schools/create.html.erb</p>

app/views/schools/destroy.html.erb
<h1>Schools#destroy</h1>
<p>Find me in app/views/schools/destroy.html.erb</p>

app/views/schools/edit.html.erb
<div class="row">
	<div  class="span6 offset3">
		<%= form_for(@school) do |f|%>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :schname,'幼儿园名称' %>
			<%= f.text_field :schname %>

app/views/schools/new.html.erb
<div class="row">
	<div class="span3 offset2">
		<%= render partial: "shared/schoolform",  locals: {school: @school}%>
	</div>
</div>

app/views/schools/search_by_location.js.erb
$(".schools_ul").html(  "<%= escape_javascript(render(@schools))%>"  )

app/views/schools/search_by_name.js.erb
$(".schools_ul").html(  "<%= escape_javascript(render(@schools))%>"  )

app/views/schools/update.html.erb
<h1>Schools#update</h1>
<p>Find me in app/views/schools/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
  <div class="alert alert-error">
   The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
   <li>*<%= msg%></li>
  <% end%>
  </ul>
  </div>
<% end%>

app/views/shared/_map.html.erb
<div id="allmap" style="width:100%;height:300px;"></div>

app/views/shared/_new.html.erb
<div class="row">
	<div class="span6 offset3">
		<%= form_for(:session, url: sessions_path) do |f| %>
			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password%>

			<%= f.submit '登录', class: "btn btn-large btn-primary" %>
		<% end %>
		<p>还没有帐号?<%= link_to "注册", signup_path %></p>
	</div>
</div>

app/views/shared/_parent.html.erb
<ul>
	<li>父母功能1</li>
	<li>父母功能2</li>
</ul>

app/views/shared/_schsidebar.html.erb
<% content_for :scripts do%>
<script type="text/javascript">
 $(document).ready(function(){
		 var cs = $("#cu_school").val();
		 if( !cs ){
			$("ul.sidebar").children("li").attr('class','disabled');			
			$("ul.sidebar li").children("a").click(function(event){
				event.preventDefault();
				alert("请先完善幼儿园基本信息!");
			});
		}
 })
</script>
<% end %>

	<ul class="nav ">
		<li><%= link_to "幼儿园信息管理", adbas_school_path(current_user.school)%></li>
		<li><%= link_to "班级管理" , adclas_school_path(current_user.school) %></li>
		<li><%= link_to "宣传页面管理", addem_school_path(current_user.school)%></li>
		<input type="hidden" id="cu_school" value="<%= current_user.school%>"/>	
	</ul>

app/views/shared/_teacher.html.erb
<ul>
	<li>幼师功能1</li>
	<li>幼师功能2</li>
</ul>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>注册帐号</h1>

<div class="row">
 <div class="span6 offset3">
   <%= form_for(@user) do |f|%>
     <%= render 'shared/error_messages', object: f.object%>
     <%= f.label :name, "姓名" %>
     <%= f.text_field :name %>
     
     <%= f.label :email, "邮箱" %>
     <%= f.text_field :email %>
     
     <%= f.label :password, "密码" %>
     <%= f.password_field :password %>
      
     <%= f.label :password_confirmation, "密码确认" %>
     <%= f.password_field :password_confirmation %>
     <br/> 
     <%= f.submit "创建帐号", class: "btn btn-large btn-primary"%>
  <% end %>
 </div>
</div>

app/views/users/select_school.html.erb
<%- 
	province = ''
	city = ''
	district = ''
	provinces  = ChinaCity.list
	cities     = ChinaCity.list(province)
	districtes = ChinaCity.list(city)
%>
<% content_for :free do %>
	<div class="row span10" style=" float:none;   border-bottom: 2px solid rgb(196, 205, 224);    border-left: 1px solid rgb(196, 205, 224);    border-right: 1px solid rgb(196, 205, 224);    border-top: 1px solid rgb(196, 205, 224); 
 background-color: rgb(231, 235, 242); 
				margin-bottom: 5px; margin-left:0px; ">
		<form accept-charset="UTF-8" action="/users/1/qschbyname" data-remote="true" method="get" style="margin:0;float:right; "><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>
				 
				<input type="text" name="name" value="按幼儿园名称搜索" style="
    height: 15px;
    font-size: small;
    margin-top: 10px;
">
				<input type="submit" class="btn btn-mini" value="搜索" style="
    margin-top: 0px;
">
</form>
</div>
<% end %>
<% content_for :main do%>
	

	<div class="row" style="border-bottom: 2px solid rgb(196, 205, 224);    border-left: 1px solid rgb(196, 205, 224);    border-right: 1px solid rgb(196, 205, 224);    border-top: 1px solid rgb(196, 205, 224);margin-left:0px; ">
	<div>
		<h4 style="/* margin-left:20px */border-bottom: 1px solid #e5e5e5;">搜索结果:</h4>
		<ul class="schools_ul">
			<%= render(@schools) || "没有找到符合条件的幼儿园!"%>
		</ul>
	</div>
			
</div>
</li>
</ul>


		</div>
<% end %>

app/views/users/select_type.html.erb
<%  content_for :main do %>
<div class="row">
  <div class="span11  user_type" style="margin-left:45px" %>
<h3 style="margin:0px;color:rgb(51,51,51)">开通服务</h3>
<p>选择您需要开通的服务类型</p>
	  <%= form_for( @user,url: update_type_user_path(@user) , html: {method: "patch"}) do |f| %>
		  <div id="select_user_type">	
	  <ul>		
		  <li>
		  <%= image_tag 'teacher.jpg',class: "img-circle"%>
		  <%= radio_button_tag(:type, 'teacher')%>
		  <%= label_tag(:type_teacher, '幼师')%>
		  </li>

		  <li>
		  <%= image_tag 'school.jpg',class: "img-circle"%>
		  <%= radio_button_tag(:type, 'school') %>
		  <%= label_tag(:type_school, '学校')%>
		  </li>

		  <li>
		  <%= image_tag 'parent.jpg',class: "img-circle"%>
		  <%= radio_button_tag(:type, 'parent') %>
		  <%= label_tag(:type_parent, '家长')%>
		  </li>
		  <%= f.submit "提交选择", class: "btn btn-large btn-primary"%>
  
	  </ul>
  </div>
  <% end %>

  
  </div>

</div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#udpate</h1>
<p>Find me in app/views/users/udpate.html.erb</p>